# Determinant Matrix


Membuat matrix identitas dengan code fungsi python untuk membuktikan determinan matrix identitas (sifat-sifat determinan).

Sifat-sifat Matrix determinan:

1. Jika baris Matrix Identitas ditukar maka akan mengubah tanda dari Determinan Matrix Identitas tersebut

2. Jika di dalam suatu Matrix ada baris atau yang merupakan kelipatan dari baris atau kolom yang lain maka det = 0.

3. Jika ada Matrix kelipatan dari matrix lain maka determinan matrix tersebut adalah kelipatan pangkat ordo kali determinan matrix dari kelipatannya.

4. Jika Determinan Matrix B adalah 2x Determinan Matrix A maka ada salah satu baris Matrix B yang menjadi 2x lipat baris Matrix A.

5. Jika ada matrix yang berasal dari penjumlahan matrix A dan matrix B maka determinannya adalah penjumlahan dari matrix A dan Matrix B.

6. Jika ada Matrix segitiga atas maka determinannya adalah perkalian anggota diagonal Matrix tersebut.

In [2]:
import numpy as np

A = np.array([[1,0],[0,1]])
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
C = np.array([[1,0,0],[0,0,1],[0,1,0]])
D = np.array([[0,1,0],[0,0,1],[1,0,0]])
E = np.array([[1,2,1],[3,1,2],[2,1,2]])
F = np.array([[3,1,2],[1,2,1],[2,1,2]])
G = np.array([[1,2,1],[2,4,2],[2,1,2]])
H = np.array([[1,2,2],[2,4,4],[1,2,3]])
I = np.array([[6,2,4],[2,4,2],[4,2,4]])
J = np.array([[3,4],[2,1]])
K = np.array([[6,8],[4,2]])
L = np.array([[2*3,2*4],[2,1]])
M = np.array([[2*3,4],[2*2,1]])
N = np.array([[4,1],[2,1]])
O = np.array([[7,5],[2,1]])
P = np.array([[2,3,2],[0,2,2],[0,0,2]])
Q = np.array([[2,1],[1,1]])
R = np.array([[1,1],[1,1]])
S = np.array([[3,3],[2,2]])


print(f"Matrix A (Identitas)=\n{A}")
print(f"Matrix B (Identitas)=\n{B}")
print(f"Matrix C =\n{C}")
print(f"Matrix D =\n{D}")
print(f"Matrix E =\n{E}")
print(f"Matrix F =\n{F}")
print(f"Matrix G =\n{G}")
print(f"Matrix H =\n{H}")
print(f"Matrix I =\n{I}")
print(f"Matrix J =\n{J}")
print(f"Matrix K =\n{K}")
print(f"Matrix L =\n{L}")
print(f"Matrix M =\n{M}")
print(f"Matrix N =\n{N}")
print(f"Matrix O =\n{O}")
print(f"Matrix P =\n{P}")
print(f"Matrix Q =\n{Q}")
print(f"Matrix R =\n{R}")
print(f"Matrix S =\n{S}")

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)
det_E = np.linalg.det(E)
det_F = np.linalg.det(F)
det_G = np.linalg.det(G)
det_H = np.linalg.det(H)
det_I = np.linalg.det(I)
det_J = np.linalg.det(J)
det_K = np.linalg.det(K)
det_L = np.linalg.det(L)
det_M = np.linalg.det(M)
det_N = np.linalg.det(N)
det_O = np.linalg.det(O)
det_P = np.linalg.det(P)
det_Q = np.linalg.det(Q)
det_R = np.linalg.det(R)
det_S = np.linalg.det(S)

print("")
print(f"Determinan Matrix A =\n{det_A}")
print("")
print(f"Determinan Matrix B =\n{det_B}")
print("")
print(f"Determinan Matrix C =\n{det_C}")
print("")
print(f"Determinan Matrix D =\n{det_D}")
print("")
print(f"Determinan Matrix E =\n{det_E}")
print("")
print(f"Determinan Matrix F =\n{det_F}")
print("")
print(f"Determinan Matrix G =\n{det_G}")
print("")
print(f"Determinan Matrix H =\n{det_H}")
print("")
print(f"Determinan Matrix I =\n{det_I}")
print("")
print(f"Determinan Matrix J =\n{det_J}")
print("")
print(f"Determinan Matrix K =\n{det_K}")
print("")
print(f"Determinan Matrix L =\n{det_L}")
print("")
print(f"Determinan Matrix M =\n{det_M}")
print("")
print(f"Determinan Matrix N =\n{det_N}")
print("")
print(f"Determinan Matrix O =\n{det_O}")
print("")
print(f"Determinan Matrix P =\n{det_P}")
print("")
print(f"Determinan Matrix Q =\n{det_Q}")
print("")
print(f"Determinan Matrix R =\n{det_R}")
print("")
print(f"Determinan Matrix S =\n{det_S}")

Matrix A (Identitas)=
[[1 0]
 [0 1]]
Matrix B (Identitas)=
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Matrix C =
[[1 0 0]
 [0 0 1]
 [0 1 0]]
Matrix D =
[[0 1 0]
 [0 0 1]
 [1 0 0]]
Matrix E =
[[1 2 1]
 [3 1 2]
 [2 1 2]]
Matrix F =
[[3 1 2]
 [1 2 1]
 [2 1 2]]
Matrix G =
[[1 2 1]
 [2 4 2]
 [2 1 2]]
Matrix H =
[[1 2 2]
 [2 4 4]
 [1 2 3]]
Matrix I =
[[6 2 4]
 [2 4 2]
 [4 2 4]]
Matrix J =
[[3 4]
 [2 1]]
Matrix K =
[[6 8]
 [4 2]]
Matrix L =
[[6 8]
 [2 1]]
Matrix M =
[[6 4]
 [4 1]]
Matrix N =
[[4 1]
 [2 1]]
Matrix O =
[[7 5]
 [2 1]]
Matrix P =
[[2 3 2]
 [0 2 2]
 [0 0 2]]
Matrix Q =
[[2 1]
 [1 1]]
Matrix R =
[[1 1]
 [1 1]]
Matrix S =
[[3 3]
 [2 2]]

Determinan Matrix A =
1.0

Determinan Matrix B =
1.0

Determinan Matrix C =
-1.0

Determinan Matrix D =
1.0

Determinan Matrix E =
-3.000000000000001

Determinan Matrix F =
3.000000000000001

Determinan Matrix G =
0.0

Determinan Matrix H =
0.0

Determinan Matrix I =
24.000000000000014

Determinan Matrix J =
-5.000000000000001

Determinan Matrix K =
-19.9999999999