# Determinant Matrix


Membuat matrix identitas dengan code fungsi python untuk membuktikan determinan matrix identitas (sifat-sifat determinan).

Sifat-sifat Matrix determinan:

1. Jika baris Matrix Identitas ditukar maka akan mengubah tanda dari Determinan Matrix Identitas tersebut

2. Jika di dalam suatu Matrix ada baris atau yang merupakan kelipatan dari baris atau kolom yang lain maka det = 0.

3. Jika ada Matrix kelipatan dari matrix lain maka determinan matrix tersebut adalah kelipatan pangkat ordo kali determinan matrix dari kelipatannya.

4. Jika Determinan Matrix B adalah 2x Determinan Matrix A maka ada salah satu baris Matrix B yang menjadi 2x lipat baris Matrix A.

5. Jika ada matrix yang berasal dari penjumlahan matrix A dan matrix B maka determinannya adalah penjumlahan dari matrix A dan Matrix B.

6. Jika ada Matrix segitiga atas maka determinannya adalah perkalian anggota diagonal Matrix tersebut.

In [5]:
import numpy as np

A = np.array([[1,0],[0,1]])
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
C = np.array([[1,0,0],[0,0,1],[0,1,0]])
D = np.array([[0,1,0],[0,0,1],[1,0,0]])
E = np.array([[1,2,1],[3,1,2],[2,1,2]])
F = np.array([[3,1,2],[1,2,1],[2,1,2]])
G = np.array([[1,2,1],[2,4,2],[2,1,2]])
H = np.array([[1,2,2],[2,4,4],[1,2,3]])
I = np.array([[6,2,4],[2,4,2],[4,2,4]])
J = np.array([[3,4],[2,1]])
K = np.array([[6,8],[4,2]])
L = np.array([[2*3,2*4],[2,1]])
M = np.array([[2*3,4],[2*2,1]])
N = np.array([[4,1],[2,1]])
O = np.array([[7,5],[2,1]])
P = np.array([[2,3,2],[0,2,2],[0,0,2]])
Q = np.array([[2,1],[1,1]])
R = np.array([[1,1],[1,1]])
S = np.array([[3,3],[2,2]])


print(f"Matrix A (Identitas)=\n{A}")
print(f"Matrix B (Identitas)=\n{B}")
print(f"Matrix C =\n{C}")
print(f"Matrix D =\n{D}")
print(f"Matrix E =\n{E}")
print(f"Matrix F =\n{F}")
print(f"Matrix G =\n{G}")
print(f"Matrix H =\n{H}")
print(f"Matrix I =\n{I}")
print(f"Matrix J =\n{J}")
print(f"Matrix K =\n{K}")
print(f"Matrix L =\n{L}")
print(f"Matrix M =\n{M}")
print(f"Matrix N =\n{N}")
print(f"Matrix O =\n{O}")
print(f"Matrix P =\n{P}")
print(f"Matrix Q =\n{Q}")
print(f"Matrix R =\n{R}")
print(f"Matrix S =\n{S}")

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)
det_E = np.linalg.det(E)
det_F = np.linalg.det(F)
det_G = np.linalg.det(G)
det_H = np.linalg.det(H)
det_I = np.linalg.det(I)
det_J = np.linalg.det(J)
det_K = np.linalg.det(K)
det_L = np.linalg.det(L)
det_M = np.linalg.det(M)
det_N = np.linalg.det(N)
det_O = np.linalg.det(O)
det_P = np.linalg.det(P)
det_Q = np.linalg.det(Q)
det_R = np.linalg.det(R)
det_S = np.linalg.det(S)

print("")
print(f"Determinan Matrix A =\n{det_A}")
print("")
print(f"Determinan Matrix B =\n{det_B}")
print("")
print(f"Determinan Matrix C =\n{det_C}")
print("")
print(f"Determinan Matrix D =\n{det_D}")
print("")
print(f"Determinan Matrix E =\n{det_E}")
print("")
print(f"Determinan Matrix F =\n{det_F}")
print("")
print(f"Determinan Matrix G =\n{det_G}")
print("")
print(f"Determinan Matrix H =\n{det_H}")
print("")
print(f"Determinan Matrix I =\n{det_I}")
print("")
print(f"Determinan Matrix J =\n{det_J}")
print("")
print(f"Determinan Matrix K =\n{det_K}")
print("")
print(f"Determinan Matrix L =\n{det_L}")
print("")
print(f"Determinan Matrix M =\n{det_M}")
print("")
print(f"Determinan Matrix N =\n{det_N}")
print("")
print(f"Determinan Matrix O =\n{det_O}")
print("")
print(f"Determinan Matrix P =\n{det_P}")
print("")
print(f"Determinan Matrix Q =\n{det_Q}")
print("")
print(f"Determinan Matrix R =\n{det_R}")
print("")
print(f"Determinan Matrix S =\n{det_S}")

Matrix A (Identitas)=
[[1 0]
 [0 1]]
Matrix B (Identitas)=
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Matrix C =
[[1 0 0]
 [0 0 1]
 [0 1 0]]
Matrix D =
[[0 1 0]
 [0 0 1]
 [1 0 0]]
Matrix E =
[[1 2 1]
 [3 1 2]
 [2 1 2]]
Matrix F =
[[3 1 2]
 [1 2 1]
 [2 1 2]]
Matrix G =
[[1 2 1]
 [2 4 2]
 [2 1 2]]
Matrix H =
[[1 2 2]
 [2 4 4]
 [1 2 3]]
Matrix I =
[[6 2 4]
 [2 4 2]
 [4 2 4]]
Matrix J =
[[3 4]
 [2 1]]
Matrix K =
[[6 8]
 [4 2]]
Matrix L =
[[6 8]
 [2 1]]
Matrix M =
[[6 4]
 [4 1]]
Matrix N =
[[4 1]
 [2 1]]
Matrix O =
[[7 5]
 [2 1]]
Matrix P =
[[2 3 2]
 [0 2 2]
 [0 0 2]]
Matrix Q =
[[2 1]
 [1 1]]
Matrix R =
[[1 1]
 [1 1]]
Matrix S =
[[3 3]
 [2 2]]

Determinan Matrix A =
1.0

Determinan Matrix B =
1.0

Determinan Matrix C =
-1.0

Determinan Matrix D =
1.0

Determinan Matrix E =
-3.000000000000001

Determinan Matrix F =
3.000000000000001

Determinan Matrix G =
0.0

Determinan Matrix H =
0.0

Determinan Matrix I =
24.000000000000014

Determinan Matrix J =
-5.000000000000001

Determinan Matrix K =
-19.9999999999

## COFACTOR EXPANSION

## MENGHITUNG INVERS MATRIX 5 X 5 DENGAN COFACTOR
menghitung matrix 5 x 5 dengan determinan dan kofaktornya

Disini saya mempunyai matrix S dengan ukuran ordo 5 x 5 sebagai berikut:

$
\begin{align*}
S=
\begin{bmatrix}
4&2&1&1&3\\
3&2&1&1&2\\
4&1&1&1&1\\
1&3&4&1&2\\
2&2&1&1&3
\end{bmatrix}
\end{align*}
$

Saya akan mencari matrix inversnya dengan menemukan determinan dan kofaktor-kofaktornya, dan diimplementasikan ke code

rumus kofaktor = $C_{ij} = (-1)^{i+j} * detS$

rumus det (pick one row or column)     = $a_{ij} * c_{ij} + a_{ij} * c_{ij} + a_{ij} * c_{ij} + a_{nn} * c_{nn}$

rumus invers matrix = ${ \frac{1}{detS}} * adj(S)$

Mencari Adjoin = $adj(S) = (kof(A))^T$

(adj(S) = Transpose dari setiap cofator-cofator Matrix)

In [17]:
import numpy as np

matrix_S = np.array([[4,2,1,1,3],[3,2,1,2,2],[4,1,1,1,1],[1,3,4,1,2],[2,2,1,1,3]])
det_Mat_S = np.linalg.det(matrix_S)
inv_Mat_S = np.linalg.inv(matrix_S)
print(f"pembuktian Determinan= {det_Mat_S}")
print(f"pembuktian Invers = \n{inv_Mat_S.round(1)}")
print()
print("="*50)
# kita mencari determinannya terlebih dahulu dengan Pick setiap row

S11 = np.array([[2,1,1,2],[1,1,1,1],[3,4,1,2],[2,1,1,3]])
S12 = np.array([[3,1,2,2],[4,1,1,1],[1,4,1,2],[2,1,1,3]])
S13 = np.array([[3,2,2,2],[4,1,1,1],[1,3,1,2],[2,2,1,3]])
S14 = np.array([[3,2,1,2],[4,1,1,1],[1,3,4,2],[2,2,1,3]])
S15 = np.array([[3,2,1,2],[4,1,1,1],[1,3,4,1],[2,2,1,1]])
S21 = np.array([[2,1,1,3],[1,1,1,1],[3,4,1,2],[2,1,1,3]])
S22 = np.array([[4,1,1,3],[4,1,1,1],[1,4,1,2],[2,1,1,3]])
S23 = np.array([[4,2,1,3],[4,1,1,1],[1,3,1,2],[2,2,1,3]])
S24 = np.array([[4,2,1,3],[4,1,1,1],[1,3,4,2],[2,2,1,3]])
S25 = np.array([[4,2,1,1],[4,1,1,1],[1,3,4,1],[2,2,1,1]])
S31 = np.array([[2,1,1,3],[2,1,2,2],[3,4,1,2],[2,1,1,3]])
S32 = np.array([[4,1,1,3],[3,1,2,2],[1,4,1,2],[2,1,1,3]])
S33 = np.array([[4,2,1,3],[3,2,2,2],[1,3,1,2],[2,2,1,3]])
S34 = np.array([[4,2,1,3],[3,2,1,2],[1,3,4,2],[2,2,1,3]])
S35 = np.array([[4,2,1,1],[3,2,1,2],[1,3,4,1],[2,2,1,1]])
S41 = np.array([[2,1,1,3],[2,1,2,2],[1,1,1,1],[2,1,1,3]])
S42 = np.array([[4,1,1,3],[3,1,2,1],[4,1,1,1],[2,1,1,3]])
S43 = np.array([[4,2,1,3],[3,2,2,2],[4,1,1,1],[2,2,1,3]])
S44 = np.array([[4,2,1,3],[3,2,1,2],[4,1,1,1],[2,2,1,3]])
S45 = np.array([[4,2,1,1],[3,2,1,2],[4,1,1,1],[2,2,1,1]])
S51 = np.array([[2,1,1,3],[2,1,2,2],[1,1,1,1],[3,4,1,2]])
S52 = np.array([[4,1,1,3],[3,1,2,2],[4,1,1,1],[1,4,1,2]])
S53 = np.array([[4,2,1,3],[3,2,2,2],[4,1,1,1],[1,3,1,2]])
S54 = np.array([[4,2,1,3],[3,2,1,2],[4,1,1,1],[1,3,4,2]])
S55 = np.array([[4,2,1,1],[3,2,1,2],[4,1,1,1],[1,3,4,1]])
print(f"Marix11 = \n{S11}")
print()
det_11 = np.linalg.det(S11)
det_12 = np.linalg.det(S12)
det_13 = np.linalg.det(S13)
det_14 = np.linalg.det(S14)
det_15 = np.linalg.det(S15)
det_21 = np.linalg.det(S21)
det_22 = np.linalg.det(S22)
det_23 = np.linalg.det(S23)
det_24 = np.linalg.det(S24)
det_25 = np.linalg.det(S25)
det_31 = np.linalg.det(S31)
det_32 = np.linalg.det(S32)
det_33 = np.linalg.det(S33)
det_34 = np.linalg.det(S34)
det_35 = np.linalg.det(S35)
det_41 = np.linalg.det(S41)
det_42 = np.linalg.det(S42)
det_43 = np.linalg.det(S43)
det_44 = np.linalg.det(S44)
det_45 = np.linalg.det(S45)
det_51 = np.linalg.det(S51)
det_52 = np.linalg.det(S52)
det_53 = np.linalg.det(S53)
det_54 = np.linalg.det(S54)
det_55 = np.linalg.det(S55)

c11 = (-1)**(1+1) * det_11
c12 = (-1)**(1+2) * det_12
c13 = (-1)**(1+3) * det_13
c14 = (-1)**(1+4) * det_14
c15 = (-1)**(1+5) * det_15
c21 = (-1)**(2+1) * det_21
c22 = (-1)**(2+2) * det_22
c23 = (-1)**(2+3) * det_23
c24 = (-1)**(2+4) * det_24
c25 = (-1)**(2+5) * det_25
c31 = (-1)**(3+1) * det_31
c32 = (-1)**(3+2) * det_32
c33 = (-1)**(3+3) * det_33
c34 = (-1)**(3+4) * det_34
c35 = (-1)**(3+5) * det_35
c41 = (-1)**(4+1) * det_41
c42 = (-1)**(4+2) * det_42
c43 = (-1)**(4+3) * det_43
c44 = (-1)**(4+4) * det_44
c45 = (-1)**(4+5) * det_45
c51 = (-1)**(5+1) * det_51
c52 = (-1)**(5+2) * det_52
c53 = (-1)**(5+3) * det_53
c54 = (-1)**(5+4) * det_54
c55 = (-1)**(5+5) * det_55

a11 = matrix_S[0][0]
a12 = matrix_S[0][1]
a13 = matrix_S[0][2]
a14 = matrix_S[0][3]
a15 = matrix_S[0][4]
a21 = matrix_S[1][0]
a22 = matrix_S[1][1]
a23 = matrix_S[1][2]
a24 = matrix_S[1][3]
a25 = matrix_S[1][4]
a31 = matrix_S[2][0]
a32 = matrix_S[2][1]
a33 = matrix_S[2][2]
a34 = matrix_S[2][3]
a35 = matrix_S[2][4]
a41 = matrix_S[3][0]
a42 = matrix_S[3][1]
a43 = matrix_S[3][2]
a44 = matrix_S[3][3]
a45 = matrix_S[3][4]
a51 = matrix_S[4][0]
a52 = matrix_S[4][1]
a53 = matrix_S[4][2]
a54 = matrix_S[4][3]
a55 = matrix_S[4][4]

# Row 1
det_S_row1 = a11*c11 + a12*c12 + a13*c13 + a14*c14 + a15*c15
print(f"det s = {det_S_row1}")
# Row 2
det_S_row2 = a21*c21 + a22*c22 + a23*c23 + a24*c24 + a25*c25
print(f"det s = {det_S_row2}")
# Row 3
det_S_row3 = a31*c31 + a32*c32 + a33*c33 + a34*c34 + a35*c35
print(f"det s = {det_S_row3}")
# Row 4
det_S_row4 = a41*c41 + a42*c42 + a43*c43 + a44*c44 + a45*c45
print(f"det s = {det_S_row4}")
# Row 5
det_S_row5 = a51*c51 + a52*c52 + a53*c53 + a54*c54 + a55*c55
print(f"det s = {det_S_row5}")
print()
Kof_Matrix_S = np.array([[c11,c12,c13,c14,c15],[c21,c22,c23,c24,c25],[c31,c32,c33,c34,c35],[c41,c42,c43,c44,c45],[c51,c52,c53,c54,c55]])
print(f"Marix dengan anggota kofaktor-kofaktornya = \n{Kof_Matrix_S}")
print()
Trans_Kof_Matrix_S = Kof_Matrix_S.transpose()
print(f"Transpose Matrix dari kofaktornya = \n{Trans_Kof_Matrix_S}")
print()
invers_S = 1 / det_S_row1 * Trans_Kof_Matrix_S
print(f"Hasil Invers Matrix adalah = \n{invers_S.round(1)}")


pembuktian Determinan= -5.999999999999996
pembuktian Invers = 
[[ 0.5  0.   0.   0.  -0.5]
 [ 5.7  2.  -4.3  0.7 -6. ]
 [-2.5 -1.   2.  -0.   2.5]
 [-2.8 -0.   1.7 -0.3  2.5]
 [-2.3 -1.   1.7 -0.3  3. ]]

Marix11 = 
[[2 1 1 2]
 [1 1 1 1]
 [3 4 1 2]
 [2 1 1 3]]

det s = -5.999999999999957
det s = -5.999999999999998
det s = -6.000000000000014
det s = -6.0
det s = -6.000000000000028

Marix dengan anggota kofaktor-kofaktornya = 
[[ -3. -34.  15.  17.  14.]
 [ -0. -12.   6.   0.   6.]
 [  0.  26. -12. -10. -10.]
 [ -0.  -4.  -0.   2.   2.]
 [  3.  36. -15. -15. -18.]]

Transpose Matrix dari kofaktornya = 
[[ -3.  -0.   0.  -0.   3.]
 [-34. -12.  26.  -4.  36.]
 [ 15.   6. -12.  -0. -15.]
 [ 17.   0. -10.   2. -15.]
 [ 14.   6. -10.   2. -18.]]

Hasil Invers Matrix adalah = 
[[ 0.5  0.  -0.   0.  -0.5]
 [ 5.7  2.  -4.3  0.7 -6. ]
 [-2.5 -1.   2.   0.   2.5]
 [-2.8 -0.   1.7 -0.3  2.5]
 [-2.3 -1.   1.7 -0.3  3. ]]
