# Determinant Matrix


membuat matrix identitas dengan code fungsi python untuk membuktikan determinan matrix identitas (sifat-sifat determinan).

In [18]:
import numpy as np

A = np.array([[1,0],[0,1]])
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
C = np.array([[1,0,0],[0,0,1],[0,1,0]])
D = np.array([[0,1,0],[0,0,1],[1,0,0]])
E = np.array([[1,2,1],[3,1,2],[2,1,2]])
F = np.array([[3,1,2],[1,2,1],[2,1,2]])
G = np.array([[1,2,1],[2,4,2],[2,1,2]])
H = np.array([[1,2,2],[2,4,4],[1,2,3]])
I = np.array([[6,2,4],[2,4,2],[4,2,4]])
J = np.array([[3,4],[2,1]])
K = np.array([[6,8],[4,2]])
L = np.array([[2*3,2*4],[2,1]])
M = np.array([[2*3,4],[2*2,1]])
N = np.array([[4,1],[2,1]])
O = np.array([[7,5],[2,1]])
P = np.array([[2,3,2],[0,2,2],[0,0,2]])
Q = np.array([[2,1],[1,1]])
R = np.array([[1,1],[1,1]])
S = np.array([[3,3],[2,2]])


print(f"Matrix A (Identitas)=\n{A}")
print(f"Matrix B (Identitas)=\n{B}")
print(f"Matrix C (Identitas)=\n{C}")
print(f"Matrix D (Identitas)=\n{D}")
print(f"Matrix E (Identitas)=\n{E}")
print(f"Matrix F (Identitas)=\n{F}")
print(f"Matrix G (Identitas)=\n{G}")
print(f"Matrix H (Identitas)=\n{H}")
print(f"Matrix I (Identitas)=\n{I}")
print(f"Matrix J (Identitas)=\n{J}")
print(f"Matrix K (Identitas)=\n{K}")
print(f"Matrix L (Identitas)=\n{L}")
print(f"Matrix M (Identitas)=\n{M}")
print(f"Matrix N (Identitas)=\n{N}")
print(f"Matrix O (Identitas)=\n{O}")
print(f"Matrix P (Identitas)=\n{P}")
print(f"Matrix Q (Identitas)=\n{Q}")
print(f"Matrix R (Identitas)=\n{R}")
print(f"Matrix S (Identitas)=\n{S}")

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)
det_E = np.linalg.det(E)
det_F = np.linalg.det(F)
det_G = np.linalg.det(G)
det_H = np.linalg.det(H)
det_I = np.linalg.det(I)
det_J = np.linalg.det(J)
det_K = np.linalg.det(K)
det_L = np.linalg.det(L)
det_M = np.linalg.det(M)
det_N = np.linalg.det(N)
det_O = np.linalg.det(O)
det_P = np.linalg.det(P)
det_Q = np.linalg.det(Q)
det_R = np.linalg.det(R)
det_S = np.linalg.det(S)

print("")
print(f"Determinan Matrix A =\n{det_A}")
print("")
print(f"Determinan Matrix B =\n{det_B}")
print("")
print(f"Determinan Matrix C =\n{det_C}")
print("")
print(f"Determinan Matrix D =\n{det_D}")
print("")
print(f"Determinan Matrix E =\n{det_E}")
print("")
print(f"Determinan Matrix F =\n{det_F}")
print("")
print(f"Determinan Matrix G =\n{det_G}")
print("")
print(f"Determinan Matrix H =\n{det_H}")
print("")
print(f"Determinan Matrix I =\n{det_I}")
print("")
print(f"Determinan Matrix J =\n{det_J}")
print("")
print(f"Determinan Matrix K =\n{det_K}")
print("")
print(f"Determinan Matrix L =\n{det_L}")
print("")
print(f"Determinan Matrix M =\n{det_M}")
print("")
print(f"Determinan Matrix N =\n{det_N}")
print("")
print(f"Determinan Matrix O =\n{det_O}")
print("")
print(f"Determinan Matrix P =\n{det_P}")
print("")
print(f"Determinan Matrix P =\n{det_Q}")
print("")
print(f"Determinan Matrix Q =\n{det_R}")
print("")
print(f"Determinan Matrix R =\n{det_S}")

Matrix A (Identitas)=
[[1 0]
 [0 1]]
Matrix B (Identitas)=
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Matrix C (Identitas)=
[[1 0 0]
 [0 0 1]
 [0 1 0]]
Matrix D (Identitas)=
[[0 1 0]
 [0 0 1]
 [1 0 0]]
Matrix E (Identitas)=
[[1 2 1]
 [3 1 2]
 [2 1 2]]
Matrix F (Identitas)=
[[3 1 2]
 [1 2 1]
 [2 1 2]]
Matrix G (Identitas)=
[[1 2 1]
 [2 4 2]
 [2 1 2]]
Matrix H (Identitas)=
[[1 2 2]
 [2 4 4]
 [1 2 3]]
Matrix I (Identitas)=
[[6 2 4]
 [2 4 2]
 [4 2 4]]
Matrix J (Identitas)=
[[3 4]
 [2 1]]
Matrix K (Identitas)=
[[6 8]
 [4 2]]
Matrix L (Identitas)=
[[6 8]
 [2 1]]
Matrix M (Identitas)=
[[6 4]
 [4 1]]
Matrix N (Identitas)=
[[4 1]
 [2 1]]
Matrix O (Identitas)=
[[7 5]
 [2 1]]
Matrix P (Identitas)=
[[2 3 2]
 [0 2 2]
 [0 0 2]]
Matrix Q (Identitas)=
[[2 1]
 [1 1]]
Matrix R (Identitas)=
[[1 1]
 [1 1]]
Matrix S (Identitas)=
[[3 3]
 [2 2]]

Determinan Matrix A =
1.0

Determinan Matrix B =
1.0

Determinan Matrix C =
-1.0

Determinan Matrix D =
1.0

Determinan Matrix E =
-3.000000000000001

Determinan Matrix F =
3.0000

Sifat-sifat Matri:

Jika di dalam suatu Matrix ada baris atau yang merupakan kelipatan dari baris atau kolom yang lain maka det = 0.

Jika ada Matrix kelipatan dari matrix lain maka determinan matrix tersebut adalah kelipatan pangkat ordo kali determinan matrix dari kelipatannya.

Jika Determinan Matrix B adalah 2x Determinan Matrix A maka ada salah satu baris Matrix B yang menjadi 2x lipat baris Matrix A

Jika ada matrix yang berasal dari penjumlahan matrix A dan matrix B maka determinannya adalah penjumlahan dari matrix A dan Matrix B

Jika ada Matrix segitiga atas maka determinannya adalah perkalian anggota diagonal Matrix tersebut