#SELAMAT BERTUGAS YA

#Menggambar persamaan bidang dalam ruang 3 dimensi


# Penyelesaian sistem linier
Penyelesaian sistem Persamaan linier dengan menggunakan eliminasi gausian

Pertama kita selesaikan persamaan berikut:

$$
8x_1+9x_2+x_3 = 19\\
x_1+2x_2+3x_3 = 9\\
2x_1+x_2+x_3 = 5\
$$


Berikut penyelesaian dari persamaan diatas

In [2]:
import numpy as np
A=np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])
print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


##Mendefinisikan fungsi operasi baris eliminasi GAUSS

* RowSwap()
=> Berfungsi unutuk menukar posisi persamaan
* RowScale()
=> Berfungsi untuk mengkalikan persamaan dengan skala
* RowAdd()
=> Berfungsi untuk menambahkan persamaan yang salah satunya sudah dikalikan dengan skala



In [3]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped. (menukarkan persamaan)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A (jumlah baris A)
    n = A.shape[1]  # n is number of columns in A (jumlah kolom A)

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale. (mengalikan entry baris A dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modified.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale. (menambahkan nilai baris k dikalikan dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B


Tahapan penyelesaian dengan menggunakan Eliminasi Gauss



In [ ]:
# Print Soal
print(A)
print("\n")

## Kurangkan 1 kali baris 0 ke baris 2
A1 = RowSwap(A,0,1)
print(A1,'\n')

A2 = RowSwap(A1,0,2)
print(A2,'\n')

A3 = RowAdd(A2,0,1,-4)
print(A3,'\n')





In [ ]:
# Print Soal
print(A)
print("\n")

## Kurangkan 1 kali baris 0 ke baris 2
A1 = RowSwap(A,0,1)
print(A1,'\n')

A2 = RowAdd(A1,0,1,-8)
print(A2,'\n')

A3 = RowAdd(A2,)


In [ ]:
# Print Soal
print(A)
print("\n")

## Tambahkan -2 kali baris 0 ke baris 1
A1 = RowAdd(A,0,1,-2)
print(A1,'\n')

## Tambahkan -4 kali baris 0 ke baris 2
A2 = RowAdd(A1,0,2,-4)
print(A2,'\n')

## Tambahkan -2 kali baris 1 ke baris 2
A3 = RowAdd(A2,1,2,-2)
print(A3,'\n')

## Kalikan baris 1 dengan 1/3
A4 = RowScale(A3,1,1.0/3)
print(A4,'\n')

## Kalikan baris 2 dengan 1/19
A5 = RowScale(A4,2,1.0/-19.)
print(A5)

In [10]:
# Matriks koefisien dan vektor hasil
A = np.array([[8, 9, 1, 19], [1, 2, 3, 9], [2, 1, 1, 5]])

# Langkah 1: Tukar baris jika diperlukan untuk membuat elemen diagonal menjadi non-zero
if A[0][0] == 0:
    for j in range(1, A.shape[0]):
        if A[j][0] != 0:
            A = RowSwap(A, 0, j)
            break
print(A)

# Langkah 2: Normalisasi baris pertama
A = RowScale(A, 0, 1.0 / A[0][0])
print(A)

# Langkah 3: Buat semua elemen di bawah diagonal menjadi nol
for i in range(1, A.shape[0]):
    A = RowAdd(A, 0, i, -A[i][0])
    print(A)
print(A)

# Langkah 1-3 untuk elemen kedua
if A[1][1] == 0:
    for j in range(2, A.shape[0]):
        if A[j][1] != 0:
            A = RowSwap(A, 1, j)
            break

A = RowScale(A, 1, 1.0 / A[1][1])

for i in range(2, A.shape[0]):
    A = RowAdd(A, 1, i, -A[i][1])

# Langkah 1-3 untuk elemen ketiga
if A[2][2] == 0:
    for j in range(3, A.shape[0]):
        if A[j][2] != 0:
            A = RowSwap(A, 2, j)
            break
print(A)
A = RowScale(A, 2, 1.0 / A[2][2])

# Tampilkan matriks setelah operasi eliminasi Gauss
print("Matriks setelah eliminasi Gauss:")
print(A)


[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]
[[1.    1.125 0.125 2.375]
 [1.    2.    3.    9.   ]
 [2.    1.    1.    5.   ]]
[[1.    1.125 0.125 2.375]
 [0.    0.875 2.875 6.625]
 [2.    1.    1.    5.   ]]
[[ 1.     1.125  0.125  2.375]
 [ 0.     0.875  2.875  6.625]
 [ 0.    -1.25   0.75   0.25 ]]
[[ 1.     1.125  0.125  2.375]
 [ 0.     0.875  2.875  6.625]
 [ 0.    -1.25   0.75   0.25 ]]
[[1.         1.125      0.125      2.375     ]
 [0.         1.         3.28571429 7.57142857]
 [0.         0.         4.85714286 9.71428571]]
Matriks setelah eliminasi Gauss:
[[1.         1.125      0.125      2.375     ]
 [0.         1.         3.28571429 7.57142857]
 [0.         0.         1.         2.        ]]
