## Aljabar Matrix
# ("Tidak mengerjakan tidak boleh masuk")
* berikan pengertian apa itu Aljabar matrix
* Operasi Matrix
* Buatlah Matrix A(3x3),B(2x3),C(3x2)
* Buat program untuk mengkalikan matrix A dan B


In [1]:
import numpy as np

In [28]:
# Matrix
A = np.array([[1,3,9],[3,-2,6],[9,4,1]]) # matrix 3x3
B = np.array([[1,7,5],[2,4,5],[1,-1,4]]) # matrix 3x3
C = np.array([[3,2],[-1,2],[3,5]]) # matrix 3x2
D = np.array([[2,4,8],[2,-1,5],[-8,5,2]]) # matrix 3x3
E = (A+B)
F = 2*(A)
G = A@C

In [20]:
print(f"Matrix A 3x3: \n{A}")
print(f" Matrix B 3x3: \n{B}")
print(f"Matrix C 3x2: \n{C}")
print(f"Matrix D 3x3: \n{D}")

Matrix A 3x3: 
[[ 1  3  9]
 [ 3 -2  6]
 [ 9  4  1]]
 Matrix B 3x3: 
[[ 1  7  5]
 [ 2  4  5]
 [ 1 -1  4]]
Matrix C 3x2: 
[[ 2 10 14]
 [ 5  2 11]
 [10  3  5]]
Matrix D 3x3: 
[[ 2  4  8]
 [ 2 -1  5]
 [-8  5  2]]


In [26]:
# Matrix A+B
E = (A+B)
print(f"Matrix E =\n{E}")

Matrix E =
[[ 2 10 14]
 [ 5  2 11]
 [10  3  5]]


In [30]:
print(f"Matrix F =\n{F}")

Matrix F =
[[ 2  6 18]
 [ 6 -4 12]
 [18  8  2]]


In [35]:
# Matrix A x C
print(A)
print()
print(B)
print()
print(f"Matrix G =\n{G}")
print(f"Ukuran Matrix = {G.shape}")

[[ 1  3  9]
 [ 3 -2  6]
 [ 9  4  1]]

[[ 1  7  5]
 [ 2  4  5]
 [ 1 -1  4]]

Matrix G =
[[27 53]
 [29 32]
 [26 31]]
Ukuran Matrix = (3, 2)


Matrix A(BxC) = Matrix (AxB)C

In [37]:
Matrix1 = A@(B@C)
Matrix2 = (A@B)@C
Matrix1 == Matrix2

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

Matrix c(AB) = Matrix (cA)B = Matrix A(cB)

In [40]:
c = 2
Matrix_3 = c*(A@B)
Matrix_4 = (c*A)@B
Matrix_5 = A@(c*B)
print(Matrix_3)
print(Matrix_4)
print(Matrix_5)

[[ 32  20 112]
 [ 10  14  58]
 [ 36 156 138]]
[[ 32  20 112]
 [ 10  14  58]
 [ 36 156 138]]
[[ 32  20 112]
 [ 10  14  58]
 [ 36 156 138]]


In [45]:
Atrans = A @ A.transpose()
