# Matrix Invers

```{contents}
```

- sifat-sifat matrix invers
- mencari invers dengan eliminasi gaus jordan
- solusi sistem persamaan linier dengan matrix invers
- (membuat soal persamaan linier 6 variabel)

## Matrix Invers

Dalam aljabar linear matrix persegi A n x n disebut invertible (atau juga disebut nonsingular, nondegenerate, atau biasanya digunakan secara umum).

Jika terdapat sebuah matrix persegi B n x n dan **AB = BA = I**, dimana I adalah dinotasikan dengan matrix Identitas n x n dan perkalian yang digunakan adalah perkalian matrix biasa. Maka Matrix B secara unik ditentukan oleh Matrix A, dan disebut Inverse dari Matrix A. dinotasikan dengan $\begin{align*}A^-1\end{align*}$. Matrix inversion adalah proses untuk menemukan invers marix dari invertible Matrix. Lain halnya Matrix persegi yang tidak dapat dibalik disebut Matrix singular atau matrix tunggal atau degenerate.



Misal Matrix
$
\begin{align*}
A =
\begin{bmatrix}
2&3\\
1&1\\
\end{bmatrix}
\end{align*}
$

Misal Matrix $
\begin{align*}
B =
\begin{bmatrix}
-1&3\\
1&-2\\
\end{bmatrix}
\end{align*}
$
Matrix AB = BA = I, Maka Matrix B adalah Matrix $\begin{align*}A^-1\end{align*}$.

Misal kita cari nilai B nya dulu yaitu invers dari matrix A, Bisa kita buktikan dengan code,

Matrix I disini adalah Matrix Identitasnya=

$$
\begin{align*}
I=
\begin{bmatrix}1&0\\
0&1
\end{bmatrix}
\end{align*}
$$

In [ ]:
# contoh Matrix A dan B 2 x 2
import numpy as np

A = np.array([[2,3],[1,1]])
B = np.array([[-1,3],[1,-2]])

print(f"A = \n{A}")
print(f"B = \n{B}")
print("\n")

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped. (menukarkan persamaan)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A (jumlah baris A)
    n = A.shape[1]  # n is number of columns in A (jumlah kolom A)

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale. (mengalikan entry baris A dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modified.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale. (menambahkan nilai baris k dikalikan dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

print(f"Matrix AB =  Matrix BA \n{A@B} =\n \n{B@A}")
print("\n")



A = 
[[2 3]
 [1 1]]
B = 
[[-1  3]
 [ 1 -2]]


Matrix AB =  Matrix BA 
[[1 0]
 [0 1]] =
 
[[1 0]
 [0 1]]




## Sifat sifat Matrix Invers

Matrix invers adalah sifat yang berlaku pada matrix yang merupakan kebalikan dari Matrix asal. Matrix invers dapat ditulis dengan simbol $\begin{align*}A^-1\end{align*}$ yang berarti jika dikalikan dengan Matrix A akan menghasilkan Matrix Identitas atau Matrix $\begin{align*}I\end{align*}$. Matrix Identitas adalah Matrix yang memiliki angka 1 sebagai diagonal utamanya dan selain itu angka 0 nilainya.

**Berikut adalah sifat sifat Matrix Invers:**
1. Matrix Invers hanya dimiliki oleh Matrix persegi atau Matrix yang memiliki baris dan kolom yang sama
2. Matrix invers hanya ada pada Matrix yang non-singular, yaitu Determinannya tidak sama dengan 0
3. Invers Matrix bersifat tunggal, artinya tidak ada matrix invers selain yang menjadi invers dari matrix tersebut. Jika B dan C adalah invers dari Matrix A, maka B = C.
4. Invers dari invers suatu Matrix adalah Matrix itu sendiri
5.  Invers dari hasil kali dua atau lebih matriks adalah hasil kali invers-inversnya dalam urutan terbalik. Jika A dan B keduanya nonsingular, maka  $\begin{align*}(AB)^-1 = B^-1 A^-1\end{align*}$.
6. **Ax = b** maka **x = $\begin{align*}A^-1\end{align*}$b** , x adalah variabel dari koefisien A, dan b adalah konstanta
7. Matrix Invers A dikali dengan A maka sama dengan Matrix Identitas. $\begin{align*}A^-1\end{align*}$ x $\begin{align*}A \end{align*}$ = $\begin{align*}I\end{align*}$


## Mencari invers dengan eliminasi gaus jordan

Dalam penerapan gauss Jordan dengan menggunakan Operasi Baris Elementer atau disebut OBE. Operai OBE terdiri dari 3 cara, yaitu:
1. Menambahkan kelipatan baris ke baris yang lain (RowAdd)
2. mengkalikan baris dengan bilangan selain nol (RowScale)
3. Menukarkan posisi baris satu dengan baris yang lain (RowSwap)

Untuk mencari Invers dari sebuah Matrix kita harus memperhatikan persamaan - persamaannya. Untuk bisa memasukkannya dalam bentuk matrix kita pisah antara koefisien yang ada disebelah ruas kiri dan konstanta yang ada disebelah ruas kanan.
contoh saya mempunyai persamaan linier 6 variabel:

$$
2X_1 + 2X_2 + 2X_3 + 4X_4 + 3X_5 + 6X_6 = 25\\
2X_1 + 2X_2 + X_3 + 4X_4 + 4X_5 + 5X_6 = 22\\
X_1 + X_2 + 3X_3 + 4X_4 + X_5 + 6X_6 = 23\\
3X_1 + 2X_2 + X_3 + X_4 + 2X_5 + 3X_6 = 16\\
2X_1 + X_2 + 2X_3 + 3X_4 + X_5 + 3X_6 = 17\\
X_1 + 2X_2 + X_3 + X_4 + 3X_5 + X_6 = 11
$$

Lalu kita akan masukkan dalam bentuk matrix:

$
\begin{align*}
KoefisienA=
\begin{bmatrix}
2&2&2&4&3&6\\
2&-2&1&4&4&5\\
1&1&3&4&1&6\\
3&2&1&1&2&3\\
2&1&2&3&1&3\\
1&2&1&1&3&1
\end{bmatrix}
\end{align*}
$
$
\begin{align*}
KonstanA=
\begin{bmatrix}
25\\
22\\
23\\
16\\
17\\
13
\end{bmatrix}
\end{align*}
$
$
\begin{align*}
I=
\begin{bmatrix}
1&0&0&0&0&0\\
0&1&0&0&0&0\\
0&0&1&0&0&0\\
0&0&0&1&0&0\\
0&0&0&0&1&0\\
0&0&0&0&0&1
\end{bmatrix}
\end{align*}
$

Jangan lupa untuk operasikan juga Matrix Identitasnya agar kita bisa cari Matrix inversnya

## Solusi sistem persamaan linier dengan matrix invers dengan 6 variabel

Untuk bisa kita menemukan invers dari suatu matrix, kita harus melakukan operasi - operasi baris elementer pada Matrix Identitas yang dimana operasi operasi baris elemternya sama dengan operasi - operasi baris elementer yang mengubah Matrix KoefisienA menjadi matrix identitas.


### Penyelesaian dengan code
Berikut adalah contoh penyelesaian mencari Invers Matrix 6x6 dengan code python. Dalam code pada Matrix A  nilai koefisien dan konstanta digabung dalam satu matrix agar mempermudah perhitungan.

In [ ]:
# Import library numpy and memasukkan persamaan dalam bentuk matrix
import numpy as np
A = np.array([[2,2,2,4,3,6],[2,2,1,4,4,5],[1,1,3,4,1,6],[3,2,1,1,2,3],[2,1,2,3,1,3],[1,2,1,1,3,1]])
print(f"Matrix A  = \n{A}")
print("\n")

b = np.array([25,22,23,16,17,13])
print(f"Matrix b =\n{b}")
print("\n")

print("Kita gabungkan setiap kolom Matrix b ke baris Matrix A")
A = np.array([[2,2,2,4,3,6,25],[2,2,1,4,4,5,22],[1,1,3,4,1,6,23],[3,2,1,1,2,3,16],[2,1,2,3,1,3,17],[1,2,1,1,3,1,13]])
print(f"Matrix A  = \n{A}")
print("\n")

print("Kita juga definisikan Matrix Identitasnya")
B  = np.array([[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]])
print(f"Matrix I = \n{B}")

Matrix A  = 
[[2 2 2 4 3 6]
 [2 2 1 4 4 5]
 [1 1 3 4 1 6]
 [3 2 1 1 2 3]
 [2 1 2 3 1 3]
 [1 2 1 1 3 1]]


Matrix b =
[25 22 23 16 17 13]


Kita gabungkan setiap kolom Matrix b ke baris Matrix A
Matrix A  = 
[[ 2  2  2  4  3  6 25]
 [ 2  2  1  4  4  5 22]
 [ 1  1  3  4  1  6 23]
 [ 3  2  1  1  2  3 16]
 [ 2  1  2  3  1  3 17]
 [ 1  2  1  1  3  1 13]]


Kita juga definisikan Matrix Identitasnya
Matrix I = 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped. (menukarkan persamaan)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A (jumlah baris A)
    n = A.shape[1]  # n is number of columns in A (jumlah kolom A)

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale. (mengalikan entry baris A dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modified.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale. (menambahkan nilai baris k dikalikan dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B


In [ ]:
print("Tukar antara baris 0 dengan baris 2")
A1 = RowSwap(A,0,2)
print(A1)
print("\n")
B1 = RowSwap(B,0,2)
print(B1)
print("\n")

print("Jumlahkan perkalian baris 0 dengan -2 ke baris 1")
A2 = RowAdd(A1,0,1,-2)
print(A2)
print("\n")
B2 = RowAdd(B1,0,1,-2)
print(B2)
print("\n")

print("Jumlahkan perkalian baris 0 dengan -2 ke baris 2")
A3 = RowAdd(A2,0,2,-2)
print(A3)
print("\n")
B3 = RowAdd(B2,0,2,-2)
print(B3)
print("\n")

print("Jumlahkan perkalian baris ke 0 dengan -3 ke baris 3")
A4 = RowAdd(A3,0,3,-3)
print(A4)
print("\n")
B4 = RowAdd(B3,0,3,-3)
print(B4)
print("\n")

print("Jumlahkan perkalian baris ke 0 dengan -2 ke baris 4")
A5 = RowAdd(A4,0,4,-2)
print(A5)
print("\n")
B5 = RowAdd(B4,0,4,-2)
print(B5)
print("\n")

print("Jumlahkan perkalian baris ke 0 dengan -1 ke baris 5")
A6 = RowAdd(A5,0,5,-1)
print(A6)
print("\n")
B6 = RowAdd(B5,0,5,-1)
print(B6)

Tukar antara baris 0 dengan baris 2
[[ 1.  1.  3.  4.  1.  6. 23.]
 [ 2.  2.  1.  4.  4.  5. 22.]
 [ 2.  2.  2.  4.  3.  6. 25.]
 [ 3.  2.  1.  1.  2.  3. 16.]
 [ 2.  1.  2.  3.  1.  3. 17.]
 [ 1.  2.  1.  1.  3.  1. 13.]]


[[0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Jumlahkan perkalian baris 0 dengan -2 ke baris 1
[[  1.   1.   3.   4.   1.   6.  23.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]
 [  2.   2.   2.   4.   3.   6.  25.]
 [  3.   2.   1.   1.   2.   3.  16.]
 [  2.   1.   2.   3.   1.   3.  17.]
 [  1.   2.   1.   1.   3.   1.  13.]]


[[ 0.  0.  1.  0.  0.  0.]
 [ 0.  1. -2.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


Jumlahkan perkalian baris 0 dengan -2 ke baris 2
[[  1.   1.   3.   4.   1.   6.  23.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]
 [  0.   0.  -4.  -4.   1.  -6. -21.]
 [  3.   2.   1.   1.   2.   3.  16.]


In [ ]:
print("Tukar baris ke 5 dengan baris ke 1")
A7 = RowSwap(A6,5,1)
print(A7)
print("\n")
B7 = RowSwap(B6,5,1)
print(B7)
print("\n")

print("Jumlahkan perkalian baris ke 1 dengan -1 ke baris 0")
A8 = RowAdd(A7,1,0,-1)
print(A8)
print("\n")
B8 = RowAdd(B7,1,0,-1)
print(B8)
print("\n")

print("Jumlahkan perkalian baris ke 1 dengan 1 ke baris 3")
A9 = RowAdd(A8,1,3,1)
print(A9)
print("\n")
B9 = RowAdd(B8,1,3,1)
print(B9)
print("\n")

print("Jumlahkan perkalian baris ke 1 dengan 1 ke baris 4")
A10 = RowAdd(A9,1,4,1)
print(A10)
print("\n")
B10 = RowAdd(B9,1,4,1)
print(B10)
print("\n")


Tukar baris ke 5 dengan baris ke 1
[[  1.   1.   3.   4.   1.   6.  23.]
 [  0.   1.  -2.  -3.   2.  -5. -10.]
 [  0.   0.  -4.  -4.   1.  -6. -21.]
 [  0.  -1.  -8. -11.  -1. -15. -53.]
 [  0.  -1.  -4.  -5.  -1.  -9. -29.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]]


[[ 0.  0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  1.]
 [ 1.  0. -2.  0.  0.  0.]
 [ 0.  0. -3.  1.  0.  0.]
 [ 0.  0. -2.  0.  1.  0.]
 [ 0.  1. -2.  0.  0.  0.]]


Jumlahkan perkalian baris ke 1 dengan -1 ke baris 0
[[  1.   0.   5.   7.  -1.  11.  33.]
 [  0.   1.  -2.  -3.   2.  -5. -10.]
 [  0.   0.  -4.  -4.   1.  -6. -21.]
 [  0.  -1.  -8. -11.  -1. -15. -53.]
 [  0.  -1.  -4.  -5.  -1.  -9. -29.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]]


[[ 0.  0.  2.  0.  0. -1.]
 [ 0.  0. -1.  0.  0.  1.]
 [ 1.  0. -2.  0.  0.  0.]
 [ 0.  0. -3.  1.  0.  0.]
 [ 0.  0. -2.  0.  1.  0.]
 [ 0.  1. -2.  0.  0.  0.]]


Jumlahkan perkalian baris ke 1 dengan 1 ke baris 3
[[  1.   0.   5.   7.  -1.  11.  33.]
 [  0.   1.  -2.  -3.   2.  -5. 

In [ ]:
print("Jumlahkan perkalian baris ke 5 dengan -1 ke baris 2")
A11 = RowAdd(A10,5,2,-1)
print(A11)
print("\n")
B11 = RowAdd(B10,5,2,-1)
print(B11)
print("\n")

print("Jumlahkan perkalian baris ke 2 dengan -5 ke baris 0")
A12 = RowAdd(A11,2,0,-5)
print(A12)
print("\n")
B12 = RowAdd(B11,2,0,-5)
print(B12)
print("\n")

print("Jumlahkan perkalian baris ke 2 dengan 2 ke baris 1")
A13 = RowAdd(A12,2,1,2)
print(A13)
print("\n")
B13 = RowAdd(B12,2,1,2)
print(B13)
print("\n")

print("Jumlahkan perkalian baris ke 2 dengan 10 ke baris 3")
A14 = RowAdd(A13,2,3,10)
print(A14)
print("\n")
B14 = RowAdd(B13,2,3,10)
print(B14)
print("\n")

print("Jumlahkan perkalian baris ke 2 dengan 6 ke baris 4")
A15 = RowAdd(A14,2,4,6)
print(A14)
print("\n")
B15 = RowAdd(B14,2,4,6)
print(B14)
print("\n")

print("Jumlahkan perkalian baris ke 2 dengan 5 ke baris 5")
A16 = RowAdd(A15,2,5,5)
print(A16)
print("\n")
B16 = RowAdd(B15,2,5,5)
print(B16)
print("\n")

Jumlahkan perkalian baris ke 5 dengan -1 ke baris 2
[[  1.   0.   5.   7.  -1.  11.  33.]
 [  0.   1.  -2.  -3.   2.  -5. -10.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0. -10. -14.   1. -20. -63.]
 [  0.   0.  -6.  -8.   1. -14. -39.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]]


[[ 0.  0.  2.  0.  0. -1.]
 [ 0.  0. -1.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.  0.]
 [ 0.  0. -4.  1.  0.  1.]
 [ 0.  0. -3.  0.  1.  1.]
 [ 0.  1. -2.  0.  0.  0.]]


Jumlahkan perkalian baris ke 2 dengan -5 ke baris 0
[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1.  -2.  -3.   2.  -5. -10.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0. -10. -14.   1. -20. -63.]
 [  0.   0.  -6.  -8.   1. -14. -39.]
 [  0.   0.  -5.  -4.   2.  -7. -24.]]


[[-5.  5.  2.  0.  0. -1.]
 [ 0.  0. -1.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.  0.]
 [ 0.  0. -4.  1.  0.  1.]
 [ 0.  0. -3.  0.  1.  1.]
 [ 0.  1. -2.  0.  0.  0.]]


Jumlahkan perkalian baris ke 2 dengan 2 ke baris 1
[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1.   0

In [ ]:
print("Jumlahkan perkalian baris ke 4 dengan -1 ke baris 3")
A17 = RowAdd(A16,4,3,-1)
print(A17)
print("\n")
B17 = RowAdd(B16,4,3,-1)
print(B17)
print("\n")

print("Jummlahkan perkalian baris ke 5 dengan -2 ke baris 3")
A18 = RowAdd(A17,5,3,-2)
print(A18)
print("\n")
B18 = RowAdd(B17,5,3,-2)
print(B18)
print("\n")

print("Jumlahkan perkalian baris ke 3 dengan 1/2 ke baris 1")
A19 = RowScale(A18,3,1/2)
print(A19)
print("\n")
B19 = RowScale(B18,3,1/2)
print(B19)
print("\n")

print("Jumlahkan perkalian baris ke 3 dengan -7 ke baris 0")
A20 = RowAdd(A19,3,0,-7)
print(A20)
print("\n")
B20 = RowAdd(B19,3,0,-7)
print(B20)
print("\n")

print("Jumlahkan perkalian baris ke 3 dengan 3 ke baris 1")
A21 = RowAdd(A20,3,1,3)
print(A21)
print("\n")
B21 = RowAdd(B20,3,1,3)
print(B21)
print("\n")

print("Jumlahkan perkalian baris ke 3 dengan 8 ke baris 4")
A22 = RowAdd(A21,3,4,8)
print(A22)
print("\n")
B22 = RowAdd(B21,3,4,8)
print(B22)
print("\n")

print("Jumlahkan perkalian baris ke 3 dengan 4 ke baris 5")
A23 = RowAdd(A22,3,5,4)
print(A23)
print("\n")
B23 = RowAdd(B22,3,5,4)
print(B23)
print("\n")

Jumlahkan perkalian baris ke 4 dengan -1 ke baris 3
[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1.   0.  -3.   0.  -3.  -4.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0.   0.  -6.  -4.  -2. -12.]
 [  0.   0.   0.  -8.  -5.  -8. -21.]
 [  0.   0.   0.  -4.  -3.  -2.  -9.]]


[[-5.  5.  2.  0.  0. -1.]
 [ 2. -2. -1.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.  0.]
 [ 4. -4. -1.  1. -1.  0.]
 [ 6. -6. -3.  0.  1.  1.]
 [ 5. -4. -2.  0.  0.  0.]]


Jummlahkan perkalian baris ke 5 dengan -2 ke baris 3
[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1.   0.  -3.   0.  -3.  -4.]
 [  0.   0.   1.   0.  -1.   1.   3.]
 [  0.   0.   0.   2.   2.   2.   6.]
 [  0.   0.   0.  -8.  -5.  -8. -21.]
 [  0.   0.   0.  -4.  -3.  -2.  -9.]]


[[-5.  5.  2.  0.  0. -1.]
 [ 2. -2. -1.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.  0.]
 [-6.  4.  3.  1. -1.  0.]
 [ 6. -6. -3.  0.  1.  1.]
 [ 5. -4. -2.  0.  0.  0.]]


Jumlahkan perkalian baris ke 3 dengan 1/2 ke baris 1
[[  1.   0.   0.   7.   4.   6.  18.]
 [  0.   1. 

In [ ]:
print("Tukar baris ke 5 dengan baris ke 4")
A24 = RowSwap(A23,5,4)
print(A24)
print("\n")
B24 = RowSwap(B23,5,4)
print(B24)
print("\n")

print("Jumlahkan perkalian baris ke 4 dengan 3 ke baris 0")
A25 = RowAdd(A24,4,0,3)
print(A25)
print("\n")
B25 = RowAdd(B24,4,0,3)
print(B25)
print("\n")

print("Jumlahkan perkalian baris ke 4 dengan -3 ke baris 1")
A26 = RowAdd(A25,4,1,-3)
print(A26)
print("\n")
B26 = RowAdd(B25,4,1,-3)
print(B26)
print("\n")

print("Jumlahkan perkalian baris ke 4 dengan 1 ke baris 2")
A27 = RowAdd(A26,4,2,1)
print(A27)
print("\n")
B27 = RowAdd(B26,4,2,1)
print(B27)
print("\n")

print("Jumlahkan perkalian baris ke 4 dengan -1 ke baris 3")
A28 = RowAdd(A27,4,3,-1)
print(A28)
print("\n")
B28 = RowAdd(B27,4,3,-1)
print(B28)
print("\n")

print("Jumlahkan perkalian baris ke 4 dengan -3 ke baris 5")
A29 = RowAdd(A28,4,5,-3)
print(A29)
print("\n")
B29 = RowAdd(B28,4,5,-3)
print(B29)
print("\n")

Tukar baris ke 5 dengan baris ke 4
[[ 1.  0.  0.  0. -3. -1. -3.]
 [ 0.  1.  0.  0.  3.  0.  5.]
 [ 0.  0.  1.  0. -1.  1.  3.]
 [ 0.  0.  0.  1.  1.  1.  3.]
 [ 0.  0.  0.  0.  1.  2.  3.]
 [ 0.  0.  0.  0.  3.  0.  3.]]


[[ 16.   -9.   -8.5  -3.5   3.5  -1. ]
 [ -7.    4.    3.5   1.5  -1.5   1. ]
 [  1.   -1.    0.    0.    0.    0. ]
 [ -3.    2.    1.5   0.5  -0.5   0. ]
 [ -7.    4.    4.    2.   -2.    0. ]
 [-18.   10.    9.    4.   -3.    1. ]]


Jumlahkan perkalian baris ke 4 dengan 3 ke baris 0
[[ 1.  0.  0.  0.  0.  5.  6.]
 [ 0.  1.  0.  0.  3.  0.  5.]
 [ 0.  0.  1.  0. -1.  1.  3.]
 [ 0.  0.  0.  1.  1.  1.  3.]
 [ 0.  0.  0.  0.  1.  2.  3.]
 [ 0.  0.  0.  0.  3.  0.  3.]]


[[ -5.    3.    3.5   2.5  -2.5  -1. ]
 [ -7.    4.    3.5   1.5  -1.5   1. ]
 [  1.   -1.    0.    0.    0.    0. ]
 [ -3.    2.    1.5   0.5  -0.5   0. ]
 [ -7.    4.    4.    2.   -2.    0. ]
 [-18.   10.    9.    4.   -3.    1. ]]


Jumlahkan perkalian baris ke 4 dengan -3 ke baris 1
[[ 1.  0. 

In [ ]:
print("Kaliakan baris 5 dengan -1/6")
A30 = RowScale(A29,5,-1/6)
print(A30)
print("\n")
B30 = RowScale(B29,5,-1/6)
print(B30)
print("\n")

print("Jumlahkan perkalian baris ke 5 dengan -5 ke baris 0")
A31 = RowAdd(A30,5,0,-5)
print(A31)
print("\n")
B31 = RowAdd(B30,5,0,-5)
print(B31)
print("\n")

print("Jumlahkan perkalian baris ke 5 dengan 6 ke baris 1")
A32 = RowAdd(A31,5,1,6)
print(A32)
print("\n")
B32 = RowAdd(B31,5,1,6)
print(B32)
print("\n")

print("Jumlahkan perkalian baris ke 5 dengan -3 ke baris 2")
A33 = RowAdd(A32,5,2,-3)
print(A33)
print("\n")
B33 = RowAdd(B32,5,2,-3)
print(B33)
print("\n")

print("Jumlahkan perkalian baris ke 5 dengan 1 ke baris 3")
A34 = RowAdd(A33,5,3,1)
print(A34)
print("\n")
B34 = RowAdd(B33,5,3,1)
print(B34)
print("\n")

print("Jumlahkan perkalian baris ke 5 dengan -2 ke baris 4")
A35 = RowAdd(A34,5,4,-2)
print(A35)
print("\n")
B35 = RowAdd(B34,5,4,-2)
A_invers = B35
print(B35)
print("\n")
print("Selesai")


Kaliakan baris 5 dengan -1/6
[[ 1.  0.  0.  0.  0.  5.  6.]
 [ 0.  1.  0.  0.  0. -6. -4.]
 [ 0.  0.  1.  0.  0.  3.  6.]
 [ 0.  0.  0.  1.  0. -1.  0.]
 [ 0.  0.  0.  0.  1.  2.  3.]
 [-0. -0. -0. -0. -0.  1.  1.]]


[[-5.          3.          3.5         2.5        -2.5        -1.        ]
 [14.         -8.         -8.5        -4.5         4.5         1.        ]
 [-6.          3.          4.          2.         -2.          0.        ]
 [ 4.         -2.         -2.5        -1.5         1.5         0.        ]
 [-7.          4.          4.          2.         -2.          0.        ]
 [-0.5         0.33333333  0.5         0.33333333 -0.5        -0.16666667]]


Jumlahkan perkalian baris ke 5 dengan -5 ke baris 0
[[ 1.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0. -6. -4.]
 [ 0.  0.  1.  0.  0.  3.  6.]
 [ 0.  0.  0.  1.  0. -1.  0.]
 [ 0.  0.  0.  0.  1.  2.  3.]
 [-0. -0. -0. -0. -0.  1.  1.]]


[[-2.5         1.33333333  1.          0.83333333  0.         -0.16666667]
 [14.        

In [ ]:
print("Matrix A menjadi Matrix Identitas setelah 35 operasi gaus jordan")
print(f"Matrix A = \n{A35}")
print("\n")
print(f"Matrix A Invers = \n{A_invers}")
print("\n")
print(f"Pembulatan Matrix A Invers = \n{A_invers.round()}")

Matrix A menjadi Matrix Identitas setelah 35 operasi gaus jordan
Matrix A = 
[[ 1.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  2.]
 [ 0.  0.  1.  0.  0.  0.  3.]
 [ 0.  0.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.  1.]
 [-0. -0. -0. -0. -0.  1.  1.]]


Matrix A Invers = 
[[-2.5         1.33333333  1.          0.83333333  0.         -0.16666667]
 [11.         -6.         -5.5        -2.5         1.5         0.        ]
 [-4.5         2.          2.5         1.         -0.5         0.5       ]
 [ 3.5        -1.66666667 -2.         -1.16666667  1.         -0.16666667]
 [-6.          3.33333333  3.          1.33333333 -1.          0.33333333]
 [-0.5         0.33333333  0.5         0.33333333 -0.5        -0.16666667]]


Pembulatan Matrix A Invers = 
[[-2.  1.  1.  1.  0. -0.]
 [11. -6. -6. -2.  2.  0.]
 [-4.  2.  2.  1. -0.  0.]
 [ 4. -2. -2. -1.  1. -0.]
 [-6.  3.  3.  1. -1.  0.]
 [-0.  0.  0.  0. -0. -0.]]


Jadi ketemu:

x1 = 1

x2 = 2

x3 = 3

x4 = 1

x5 = 1

x6 = 1

Lalu kita substitusikan ke salah satu persamaan. Misal: X_1 + 2X_2 + X_3 + X_4 + 3X_5 + X_6 = 13

Diperoleh => 1 + 2.2 + 1.3 + 1 + 3.1 + 1 = 13

Hasilnya  => 13 =13

Jadi Invers dari
$
\begin{align*}
MatrixA=
\begin{bmatrix}
2&2&2&4&3&6\\
2&-2&1&4&4&5\\
1&1&3&4&1&6\\
3&2&1&1&2&3\\
2&1&2&3&1&3\\
1&2&1&1&3&1
\end{bmatrix}
\end{align*}
$
adalah =
$
\begin{align*}
MatrixA^-1=
\begin{bmatrix}
-2&1&1&1&0&0\\
11&-6&-6&-2&2&0\\
-4&2&2&1&-0&0\\
4&-2&-2&-1&1&0\\
6&3&3&1&-1&0\\
-0&0&0&0&-0&0
\end{bmatrix}
\end{align*}
$


Pembuktian Nomor 6:

**Ax = b** maka **x = $\begin{align*}A^-1\end{align*}$b**

In [ ]:

b = np.array([25,22,23,16,17,13])
print("Ax = b")
print(f"Ax = {b}")

print("\n")
print("x = A^-1 b")
print(f"x = {B35 @ b}")

Ax = b
Ax = [25 22 23 16 17 13]


x = A^-1 b
x = [1. 2. 3. 1. 1. 1.]


Pembuktian Nomor 7:

$\begin{align*}A^-1\end{align*}$ x $\begin{align*}A \end{align*}$ = $\begin{align*}I\end{align*}$

In [ ]:
C = A_invers @ A
print("A_invers x A = I")
print(f"A_invers x A =\n{C.round()}")

A_invers x A = I
A_invers x A =
[[ 1.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  2.]
 [ 0.  0.  1.  0.  0.  0.  3.]
 [-0. -0. -0.  1. -0. -0.  1.]
 [ 0.  0.  0.  0.  1.  0.  1.]
 [-0. -0. -0. -0. -0.  1.  1.]]


baris 1 A Invers dikalikan b

In [ ]:
Ai = A_invers.round(5)

print(Ai)
print("\n")
b = np.array([25,22,23,16,17,13])
b = b.transpose()
print(b)
print("\n")
# print("\n")
# print(A_1 @ b)
# print("\n")
A1 = Ai[0,:]
A2 = Ai[1,:]
A3 = Ai[2,:]
print(f"A1 = {A1}")
print(f"A2 = {A2}")
print(f"A3 = {A3}")
print("\n")
print(b)
# print(A1)
# b.shape
# print(A1@b)
# c = A1 @ b
print(A1@b)
print(A2@b)
print(A3@b)

[[-2.5      1.33333  1.       0.83333  0.      -0.16667]
 [11.      -6.      -5.5     -2.5      1.5      0.     ]
 [-4.5      2.       2.5      1.      -0.5      0.5    ]
 [ 3.5     -1.66667 -2.      -1.16667  1.      -0.16667]
 [-6.       3.33333  3.       1.33333 -1.       0.33333]
 [-0.5      0.33333  0.5      0.33333 -0.5     -0.16667]]


[25 22 23 16 17 13]


A1 = [-2.5      1.33333  1.       0.83333  0.      -0.16667]
A2 = [11.  -6.  -5.5 -2.5  1.5  0. ]
A3 = [-4.5  2.   2.5  1.  -0.5  0.5]


[25 22 23 16 17 13]
0.9998299999999958
2.0
3.0


In [ ]:
!free -g


               total        used        free      shared  buff/cache   available
Mem:              12           0           8           0           3          11
Swap:              0           0           0
