In [2]:
import numpy as np


In [9]:
# buat matrix A (5x5)

A = np.array([[4,2,1,1,3],[3,2,1,2,2],[4,1,1,1,1],[1,3,4,1,2],[2,2,1,1,3]])
print(f'matrix A  = \n{A}')


matrix A  = 
[[4 2 1 1 3]
 [3 2 1 2 2]
 [4 1 1 1 1]
 [1 3 4 1 2]
 [2 2 1 1 3]]


In [10]:
# mencari invers matrix dengan fungsi numpy np.linalg.inv
print(f'A invers = \n{np.linalg.inv(A).round(2)}')

A invers = 
[[ 0.5   0.    0.    0.   -0.5 ]
 [ 5.67  2.   -4.33  0.67 -6.  ]
 [-2.5  -1.    2.   -0.    2.5 ]
 [-2.83 -0.    1.67 -0.33  2.5 ]
 [-2.33 -1.    1.67 -0.33  3.  ]]


In [12]:
B = A @ np.linalg.inv(A)
print(B.round(1))

[[ 1. -0. -0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [-0. -0.  1. -0.  0.]
 [ 0.  0. -0.  1.  0.]
 [-0. -0. -0. -0.  1.]]


In [8]:
# A_inv = 1/det_A * adj A

A_det = np.linalg.det(A)

print(A_det)



54.999999999999964
